### ISSUE TITLE
Button text in Passcode Theming is hard-coded to white, which means it's invisible on iOS stock light mode

### ISSUE THREAD

**Issue by CubeBag** [s8ngyu/Mugunghwa#11]
<img src="https://user-images.githubusercontent.com/17459634/194735141-38c4f182-9a8f-4d9f-8213-e13c6cf5c874.PNG" data-canonical-src="https://user-images.githubusercontent.com/17459634/194735141-38c4f182-9a8f-4d9f-8213-e13c6cf5c874.PNG" height=400 />

<img src="https://user-images.githubusercontent.com/17459634/194735147-f8393ed7-cfe1-4493-a5b6-077f4d319a0e.PNG" data-canonical-src="https://user-images.githubusercontent.com/17459634/194735147-f8393ed7-cfe1-4493-a5b6-077f4d319a0e.PNG" height=400 />

**Comment by s8ngyu** [comment]
Are you on iOS 14?

**Comment by CubeBag** [comment]
Yes

**Comment by s8ngyu** [comment]
SwiftUI lacks so much features on iOS 14. That's why the background of the button is gone. I'll fix that in the next release.

**Comment by s8ngyu** [comment]
this was fixed in the latest release
