### ISSUE TITLE
Icons revert to stock icon after updating in app store

### ISSUE THREAD

**Issue by yaboijay2029** [s8ngyu/Mugunghwa#18]
iPhone 11 Pro Max, iOS 15.1

reverted to default theme and reapplied custom theme (Felicity Pro). Rebuilt icon cache and respiring. No change

**Comment by HuChundong** [comment]
it replace the icon in app's assets, so i think after update, you need to apply theme again.

**Comment by yaboijay2029** [comment]
I tried it. It bought a couple back but not all…not sure what else to try.

**Comment by s8ngyu** [comment]
This is a normal behaviour. Themed assets are overwritten when the app is updated. You need to theme it again after app updating.
