### ISSUE TITLE
Crash when applying theme

### ISSUE THREAD

**Issue by skelitonlord** [s8ngyu/Mugunghwa#26]
Link to crash log: https://pastebin.com/EMJpgkvH

Ipados 15.1 latest trollstore mugunghwa

**Comment by skelitonlord** [comment]
Since the previous report was prior to 3.0 release I didn't post it within that issue. If it is a duplicate I apologize

**Comment by sourcelocation** [comment]
Same

**Comment by s8ngyu** [comment]
3e20078 fixed this issue
