### ISSUE TITLE
lock screen

### ISSUE THREAD

**Issue by Nm12-GH** [s8ngyu/Mugunghwa#3]
![image](https://user-images.githubusercontent.com/74898933/190920907-a6a7d368-ddd0-46c4-b869-38b58f0517da.png)

The light and camera areas are not displayed correctly
iOS15.0,iPhone 8
(I used Translation)

**Comment by s8ngyu** [comment]
This is the limit without tweak injection. Currently, Mugunghwa sets device layout to iPhone XS's. I'll look into a better way to get Home Gesture properly.

**Comment by Macleykun** [comment]
> Okay, thank you very much.

could you close the issue since ya got the solution/answer :)
