### ISSUE TITLE
Gestures Homescreen

### ISSUE THREAD

**Issue by JMillz269** [s8ngyu/Mugunghwa#4]
iPhone 6s+ on iOS 15.4.1. Home gestures make the homescreen icons/spacing get wonky. Status bar time isn't even spaced either (the time is higher than other icons). Unsure if this is actually fixable without tweak injection or not. Pictures for reference. Cool it can be done without a full jailbreak regardless!
![AC45FB8A-1DC3-4209-9C99-28F448F6DAF7](https://user-images.githubusercontent.com/24706996/190927626-d6de5b35-f4f1-4fa0-86b6-7cf62f76c262.png)

**Comment by s8ngyu** [comment]
duplicate #3
