### ISSUE TITLE
Tapping on Utilities instantly crashes the app, iPhone 11 Pro Max 15.1

### ISSUE THREAD

**Issue by enaloha** [s8ngyu/Mugunghwa#6]
As the subject says. Tapping on Utilities crashes the app. Respring does not help and reboot doesn't either. I should add that this happens with both 2.x versions; the 1.0.1 version does not crash, but lacks the passcode theming...

**Comment by s8ngyu** [comment]
I am aware that the algorithm passcode theming uses causes the crash. I am fixing it right now and the update should be up in one or two days. I will let you know in this thread when It's fixed.

**Comment by sudo9000** [comment]
> I am aware that the algorithm passcode theming uses causes the crash. I am fixing it right now and the update should be up in one or two days. I will let you know in this thread when It's fixed.

How is that one or two day update coming from 7 days ago?

**Comment by s8ngyu** [comment]
@enaloha @sudo9000 Version 2.0.2 is out. Please check this version out and let me know if this fixed the issue.

https://github.com/s8ngyu/Mugunghwa/releases/tag/2.0.2

**Comment by enaloha** [comment]
Thanks for updating. Just tested, and sorry to report that it still crashes instantly on my device. Respring... still crashes. Reboot... still crashes.

**Comment by s8ngyu** [comment]
@enaloha How about version 2.0.3?

**Comment by enaloha** [comment]
still no go unfortunately

**Comment by s8ngyu** [comment]
@enaloha Can you send me a crash log?
Please follow this step below.
https://twitter.com/soongyu_kwon/status/1573635808225300480?s=20&t=UqjDpMZLBdmTHZTyy3bQFQ

**Comment by s8ngyu** [comment]
@enaloha Seems like your device has different files. Can you please install following `.ipa` to send diagnostics to analytics@soongyu.me?
https://we.tl/t-9E8Ie4OJOq

**Comment by s8ngyu** [comment]
@enaloha Have you ever touched `/var/mobile/Library/Caches/TelephonyUI-8/` manually or with other tools like Jaility?
It seems like you have some junk files in that folder.

**Comment by enaloha** [comment]
in case you are interested, this is what I have in /var/mobile/Library/Caches/TelephonyUI-8/ (it’s my theme for the dialer). Should I delete those icons and see if that fixes the crash?

**Comment by s8ngyu** [comment]
Delete all files in `TelephonyUI-8`  and folder named `Telephone` at `/var/mobile/mugunghwa/`. After that, reboot and retry. These steps should regenerate all necessary files.

**Comment by enaloha** [comment]
So I deleted all files in var/mobile/Library/Caches/TelephonyUI-8 (note the file is owner/group as mobile/mobile and permissions are RWE/RE/RE
There is no Telephone folder mungunghwa (actually, var/mobile/mugunghwa is completely empty after fresh install and opening the app.

**Comment by enaloha** [comment]
Sorry, sent email before finishing:

So I deleted all files in var/mobile/Library/Caches/TelephonyUI-8 (note the file is owner/group as mobile/mobile and permissions are RWE/RE/RE
There is no Telephone folder mungunghwa (actually, var/mobile/mugunghwa is completely empty after fresh install and opening the app.

Still the app crashes instantly when tapping on Utilities (respring, reboot, re-install don’t fix the crash either)

**Comment by enaloha** [comment]
Just successfully futurerestored to 15.4.1, re-installed Trollstore and re-downloaded the ipas I had in Trollstore and they all seem to work fine. I also re-installed Mugunghwa, but now it crashes instantly (not just when tapping on Utilities).

**Comment by s8ngyu** [comment]
That would be great.

**Comment by enaloha** [comment]
analytics sent

**Comment by enaloha** [comment]
yes, my phone was jailbroken before (14.9 with unc0ver) and I have themed the dialer and passcode icons using winterboard. I have then upgraded to 15.1 when everybody said the jb would be done in a week or too (yeah, right). So I assume that there are still some residues of the jb around...

**Comment by Tawnee323** [comment]
Hey so I’m having the same problem. Seeing as it hasn’t been fixed I sent a crash log to the support email

**Comment by mreser99** [comment]
iPhone 8 Plus also crashing when tapping to utilities. 2.0.3

**Comment by s8ngyu** [comment]
Looks like you got multiple Telephony UI somehow, and Mugunghwa was coded to expect only one. This should be fixed in the next build.

**Comment by enaloha** [comment]
Yeah, I am theming the passcode and the phone dialer icons manually via Filza. To make that easier, I store my themes in two locations to accomplish this:

Pass: /var/mobile/Library/Caches/TelephonyUI-8
Dialer: /var/mobile/Containers/Data/Application/Phone/Library/Caches/TelephonyUI-8

This way, I can go into Filza and simply rename the folders appropriately to switch themes. BTW, can you also enable the dialer theming? I assume, this would need some individual setting to tell Mugunghwa the name of the user's Phone.app (this is different for each device). Anyway, here are my two themes in use right now:

![pass](https://user-images.githubusercontent.com/13284542/196050808-31c071d4-7e74-4652-863d-386d17657660.jpg) ![dialer](https://user-images.githubusercontent.com/13284542/196050815-bae92e19-521a-46e7-9712-7c903fc191cd.jpg)

**Comment by enaloha** [comment]
Update: I have renamed the extra folders so they don't start with TelephonyUI-8 and Mugunghwa no longer crashes

**Comment by s8ngyu** [comment]
Yeah, I found out that you have "TelephonyUI-7 Metal" and etc in the caches folder. System apps are stored at /Applications which is not accessible with the current permission that TrollStore gives, that's the reason why it cannot theme those. The random folder name issue you mentioned also a thing for non-system apps theming, it's solved by checking container metadata.

Closing this issue as it's solved.

**Comment by Tawnee323** [comment]
Is says resolved, but what’s the fix?

**Comment by Tawnee323** [comment]
Which TelephoneyUI-8 should I change wand which should I keep? I have one in 

/var/mobile/Library/Caches/TelephonyUI-8

and one in

var/mobile/Containers/Data/Application/Phone/Library/Caches/TelephonyUI-8

**Comment by enaloha** [comment]
Mugunghwa does not presently theme the phone dialer in var/mobile/Containers/Data/Application/Phone/Library/Caches/TelephonyUI-8 (I theme the dialer manually by replacing Apple's PNGs with my theme. Mugunghwa themes the passcode, which is found here: /var/mobile/Library/Caches/TelephonyUI-8

If you only have one folder whose name begins with "TelephonyUI-8", then your crash is not related to multiple TelephonyUI folders in /var/mobile/Library/Caches/ and you should follow s8ngyu's suggestion he posted here: https://github.com/s8ngyu/Mugunghwa/issues/13

**Comment by Tawnee323** [comment]
All he does in that thread is link back to this one?

**Comment by enaloha** [comment]
Okay, you really should read what he says. Quote from his post:

> If that thread doesn't fix the issue, please send me a crash log following this tutorial below.
> https://twitter.com/soongyu_kwon/status/1573635808225300480?s=20&t=UqjDpMZLBdmTHZTyy3bQFQ

**Comment by Tawnee323** [comment]
I did that a while ago
